language: java
services:
- docker
env:
  global:
script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  docker build . --tag devops_eksamen --build-arg JAR_FILE=./devops_eksamen-0.0.1-SNAPSHOT.jar
  docker tag  devops_eksamen  bragefridriksson/ devops_eksamen docker push bragefridriksson/devops_eksamen
